name: OSSAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '29 14 * * 6'

permissions:
  contents: read

jobs:
  OSSAR-Scan:
    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest support coming soon
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

      # Install Node.js
      # The OSSAR action is now a JavaScript action, so we need to install Node.js on the runner.
      # GitHub hosted runners already have Node.js installed, so this step can be skipped for self-hosted runners.
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

      # Run open source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@v2
      id: ossar

      # Upload results to the Security tab
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
